name: publish package to serverless-hub

on:
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine
          pip install requests

      - name: fc-mysql-python
        env:
          publish_token: ${{ secrets.alibaba_registry_publish_token }}
        run: |
          cd mysql
          wget https://serverless-registry.oss-cn-hangzhou.aliyuncs.com/publish-file/python3/hub-publish.py
          ls
          python hub-publish.py
          cd ..

      - name: fc-mongodb-python
        env:
          publish_token: ${{ secrets.alibaba_registry_publish_token }}
        run: |
          cd mongodb
          wget https://serverless-registry.oss-cn-hangzhou.aliyuncs.com/publish-file/python3/hub-publish.py
          ls
          python hub-publish.py
          cd ..

      - name: fc-sql-server-python
        env:
          publish_token: ${{ secrets.alibaba_registry_publish_token }}
        run: |
          cd sql_server
          wget https://serverless-registry.oss-cn-hangzhou.aliyuncs.com/publish-file/python3/hub-publish.py
          ls
          python hub-publish.py
          cd ..

      - name: fc-redis-python
        env:
          publish_token: ${{ secrets.alibaba_registry_publish_token }}
        run: |
          cd redis
          wget https://serverless-registry.oss-cn-hangzhou.aliyuncs.com/publish-file/python3/hub-publish.py
          ls
          python hub-publish.py
          cd ..